AVALIA_COLLECTION_EXAMPLE = [
    {
        "user": "Mano_El",
        "name": "Resort_Muro_Alto",
        "rate_local": 9,
        "rate_service": 6,
        "rate_structure": 7,
        "rate_clean": 8,
        "rate_confort": 6,
        "rate_offer": 6,
        "rate_comment": "",
        "rate_general": 7,
    },
    {
        "user": "Charli",
        "name": "Resort_Muro_Alto",
        "rate_local": 4,
        "rate_service": 4,
        "rate_structure": 4,
        "rate_clean": 4,
        "rate_confort": 4,
        "rate_offer": 4,
        "rate_comment": "Muito ruim!",
        "rate_general": 4,
    },
    {
        "user": "Charli",
        "name": "Maracabana_Spa",
        "rate_local": 3,
        "rate_service": 9,
        "rate_structure": 9,
        "rate_clean": 10,
        "rate_confort": 9,
        "rate_offer": 5,
        "rate_comment": "A localização é um impasse, porém pode valer a pena!",
        "rate_general": 7.5,
    },
    {
        "user": "Johannah",
        "name": "Maracabana_Spa",
        "rate_local": 4,
        "rate_service": 8,
        "rate_structure": 8,
        "rate_clean": 9,
        "rate_confort": 9,
        "rate_offer": 6,
        "rate_comment": "Não sei se repetiria",
        "rate_general": 7.3,
    },
    {
        "user": "Zezinho",
        "name": "Pousada_Sumare",
        "rate_local": 8,
        "rate_service": 8,
        "rate_structure": 8,
        "rate_clean": 8,
        "rate_confort": 8,
        "rate_offer": 8,
        "rate_comment": "Experiência excelente!",
        "rate_general": 8,
    },
    {
        "user": "Zezinho",
        "name": "Pousada_Sumare",
        "rate_local": 8,
        "rate_service": 6,
        "rate_structure": 5,
        "rate_clean": 5,
        "rate_confort": 5,
        "rate_offer": 4,
        "rate_comment": "Decaiu o nível desde minha última visita",
        "rate_general": 5.5,
    }
]